apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoso-prod

bases:
  - ../../../../base/01-apps/contoso

images:
  - name: contoso
    newName: quay.io/pittar/contoso
    newTag: latest