apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contoso
    app.kubernetes.io/component: contoso-app
    app.kubernetes.io/instance: contoso
    app.kubernetes.io/part-of: contoso-app
    app.openshift.io/runtime-namespace: dotnet
  name: contoso
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: contoso
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contoso
        deploymentconfig: contoso
    spec:
      containers:
        - image: quay.io/pittar/contoso:latest
          imagePullPolicy: Always
          name: contoso
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30