apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoso-test

bases:
  - ../../../../base/01-apps/contoso

images:
  - name: image-registry.openshift-image-registry.svc:5000/contoso-cicd/contoso
    newName: image-registry.openshift-image-registry.svc:5000/contoso-cicd/contoso
    newTag: test
