apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoso-test

bases:
  - ../../../../base/01-apps/contoso

images:
  - name: quay.io/vazonline/contoso
    newName: quay.io/vazonline/contoso
    newTag: test
