apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-canada-gitops/catalog/openshift-pipelines-tasks/rollout-restart/base?ref=master


resources:
  - git-task.yaml
  - create-pr-task.yaml
  - tag-and-push-image-task.yaml
  - generate-id-task.yaml
  - dotnet-sdk-task.yaml
  - dontnet-sdk-sonar-task.yaml
  - kustomize-task.yaml

