apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Main namespaces project.
  - namespaces-project.yaml
  # Tooling Namespaces
  - cicd-tools-app.yaml
  # Pet Clinic Namespaces
  - contoso-cicd-app.yaml
  - contoso-dev-app.yaml
  - contoso-test-app.yaml