apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-cicd

bases:
  - 01-tasks
  - 02-pipelines
  - 03-triggers
  - 04-secrets

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cicd-image-puller
    path: cicd-image-puller-rolebinding-patch.yaml