apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-cicd

bases:
  - 01-tasks
  - 02-pipelines
  - 03-triggers
  - 04-secrets

resources:
  - pipeline-serviceaccount.yaml