apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Main namespaces project.
  - namespaces-project.yaml
  # Contoso Namespaces
  - contoso-prod-app.yaml
